---
title: "Figure 4b _data"
output:
  pdf_document: default
  pdf_notebook: default
---

```{r}
library(readr)
library(pathview)
library(data.table)
```
```{r}
#pathview.csv from KNIME folder "Figure4_RNA_seq"
ko_test <- read.csv("pathview.csv", sep = ",",header = TRUE, row.names = 1)
as.matrix(ko_test) -> ko_mat
```

```{r}
# run with ko numbers centred values---------------------
#"04150" = mTOR signaling
# 04630 Jak-STAT signaling pathway (23)
# 04064 NF-kappa B signaling pathway (28)
# 04668 TNF signaling pathway (35)
# 04350 TGF-beta signaling pathway (38)
# 04010 MAPK signaling pathway (110)
# 04620 Toll-like receptor signaling pathway (23)
# 00480 Glutathion pathway
# 04610 Complement and coagulation cascades
# 04621 NOD-like receptor
# 04625 C-type lectin receptor signaling pathway
# 05145  	Toxoplasmosis

my_pathways <- c("04064", "04620")
```
```{r}
pv_ko.out <-   pathview(gene.data = ko_mat[, c(2,3,4)], 
                      pathway.id = my_pathways,  #pathways of interest
                      species = "ko", # ko
                      out.suffix = "Centered_Sym_Apo_Mg", 
                      limit = list(gene = 7, cpd = 1), 
                      gene.idtype = "kegg",
                      kegg.native = TRUE, 
                      low = list(gene = "firebrick3", cpd = "firebrick3"), #set colors
                      mid = list(gene = "gray", cpd = "gray"),  # set colors
                      high = list(gene = "dodgerblue3", cpd = "dodgerblue3")) # set colors

pv_ko.out <- pathview(gene.data = ko_mat[, c(6,7,10)], 
                      pathway.id = my_pathways,  #pathways of interest
                      species = "ko", 
                      out.suffix = "Significant_Sym-vs-Apo_Sym-vs-Sym-Apo_Sym-vs-Mg", # ko
                      limit = list(gene = 7, cpd = 1), 
                      gene.idtype = "kegg",
                      kegg.native = TRUE, 
                      low = list(gene = "firebrick3", cpd = "firebrick3"), #set colors
                      mid = list(gene = "gray", cpd = "gray"),  # set colors
                      high = list(gene = "dodgerblue3", cpd = "dodgerblue3")) # set colors
```

