---
title: "Figure 2d"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
```{r}
library(readxl) 
library(lubridate)
library(mgcv)
library(ggplot2)
library(ggsignif)
library(readr)
library(emmeans)
library(tidyr)
library(plyr)
library(dplyr)
```

```{r}
#load in raw data
dat <- data.frame(read_csv("2d+e_data.csv"))
head(dat)
```
```{r}
#clean up raw data
dat$Algae <- factor(dat$Algae, levels= c("SSB01", "M. gaditana", "N. oculata", "C. velia"))
dat$Well_ID <- factor(dat$Well_ID)
dat$Treatment <- factor(dat$Treatment)
dat$Repeat.Date. <- factor(as.character(dat$Repeat.Date.))
dat$Expulsion <- ifelse(dat$Time_to_first_expulsion<720,1,0)
head(dat)
```
```{r}
#model data with generalized linear mixed modes 
mod <- gam(Expulsion ~ Algae + s(Well_ID, bs="re"),data=dat,family=binomial())
S <- summary(mod)$p.table
S
```
```{r}
#model pairwise comparison (Tukey)
mod.emm.s <-  emmeans(mod, "Algae")
mod.emm.s <-  emmeans(mod, "Algae")
pairwise <- data.frame(pairs(mod.emm.s))
pairwise$label <- ifelse(pairwise$p.value < 0.001, "***",ifelse(pairwise$p.value < 0.01, "**",ifelse(pairwise$p.value < 0.05, "*","" )))
pairwise <- pairwise %>%  separate(contrast, c("start", "end"), " - ")
write_csv(pairwise, "2d_pairwise.csv")
```
```{r}
#clean up results for graph
result <- data.frame(mod.emm.s)
summary <- data.frame(Algae=result$Algae)
#Transform data (linkfunction)
summary$mean<- plogis(result$emmean)
summary$down <- plogis(result$lower.CL)
summary$up <- plogis(result$upper.CL)
head(summary)
write_csv(summary, "2d_summary.csv")
```

```{r}
# prepair for geom_signif
signi <- data.frame(start = factor(pairwise$start))
signi$end <- factor(pairwise$end)
signi$label <- factor(pairwise$label)
signi <- filter(signi, label != "")
signi$y <- seq(0.975, length.out=nrow(signi), by=-0.025)
signi
```

```{r}
#Plot graph
P1<-ggplot(data = summary) +
  geom_bar(aes(x = Algae, y = mean),stat = "identity", fill = c("#FF2500","#E0D532","#008D58","#0067A2"))  +
  geom_errorbar(aes(x = Algae, y = mean, ymin=down, ymax=up), width=.5) +
  theme_classic() +
  geom_signif(data = signi , aes(xmin = start, xmax = end, annotations = label, y_position = y),  tip_length = 0, textsize = 5, vjust = 0.75, manual = TRUE) +
  labs(x = "", y = "Fraction of expelled algae") +
  scale_y_continuous(expand = c(0, 0), limits = c(0,1))
plot(P1)
ggsave("Figure_2d.pdf",width=7.6,height=11,units="cm")
```

```{r}
# get n count per treatment
ndat <- ddply(dat, c("Algae", "Treatment", "Repeat.Date."), summarise,
               N    = length(Larvae))
n_Figure <-  ddply(ndat, c("Algae", "Treatment"), summarise,
               N    = length(Repeat.Date.))
n_Figure
write_csv(n_Figure, "2d_n.csv")
````



