---
title: "Figure 1D"
output:
  pdf_document: default
  html_document:
    df_print: paged
---

```{r}
library(readxl)
library(lubridate)
library(mgcv)
library(ggplot2)
library(ggsignif)
library(readr)
library(emmeans)
library(tidyr)
library(plyr)
library(dplyr)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Cmd+Option+I*.
```{r}
dat <- data.frame(read_csv("1d+e_data.csv"))
head(dat)
```
```{r}
dat$Algae <- factor(dat$Algae, levels= c("SSB01", "M. gaditana", "N. oculata", "C. velia"))
dat$Well_ID <- factor(dat$Well_ID)
dat$Time_post_infection <- factor(as.double(dat$Time_post_infection))
dat$Repeat.Date. <- factor(as.character(dat$Repeat.Date.))
dat$infected <- ifelse(dat$Number.of.Symbionts>=1,1,0)
head(dat)
```
```{r}
#model data with generalized linear mixed modes
mod <- gam(infected ~ Algae + Time_post_infection + s(Well_ID, bs="re"),data=dat,family=binomial())
S <- summary(mod)$p.table
S
```
```{r}
#model pairwise comparison (Tukey)
mod.emm.s <-  emmeans(mod, c("Algae","Time_post_infection"))
pairwise <- data.frame(pairs(mod.emm.s))
pairwise$label <- ifelse(pairwise$p.value < 0.001, "***",ifelse(pairwise$p.value < 0.01, "**",ifelse(pairwise$p.value < 0.05, "*","" )))
pairwise <- pairwise %>%  separate(contrast, c("start", "end"), " - ")
pairwise <- pairwise %>%  separate(start, c("Algae_1", "t.p.i_1"),  sep="\\s+(?=\\S*$)")
pairwise <- pairwise %>%  separate(end, c("Algae_2", "t.p.i_2"),  sep="\\s+(?=\\S*$)")
head(pairwise)
write_csv(pairwise, "1d_pairwise.csv")
```
```{r}
result <- data.frame(mod.emm.s)
summary <- data.frame(Algae=result$Algae)
#Transform data (linkfunction)
summary$Time_post_infection <- as.numeric(as.character(result$Time_post_infection))
summary$mean<- plogis(result$emmean)
summary$down <- plogis(result$lower.CL)
summary$up <- plogis(result$upper.CL)
summary
write_csv(summary, "1d_summary.csv")
```

```{r}
P1 <- ggplot(data = summary) + 
  geom_line(aes(x = Time_post_infection, y = mean, color = Algae),show.legend = FALSE)+ 
  geom_errorbar(aes(x = Time_post_infection, group=Algae, y = mean, ymin=down, ymax=up, color = Algae), width=.5, show.legend = FALSE) +
  theme_classic() +
  scale_color_manual(breaks = c("SSB01", "M. gaditana", "N. oculata", "C. velia"),
                     values=c("#FF2500","#E0D532","#008D58","#0067A2")) +
  labs(x = "Time post infection (d)", y = "Fraction of infected larvae") +
  scale_y_continuous(expand = c(0, 0),limits = c(0,1)) +
  scale_x_continuous(breaks = c(1,2,3,6,10)) +
  geom_vline(xintercept = 1, linetype  = 2)
plot(P1)
ggsave("Figure_1d.pdf",width=16,height=11,units="cm")
```
```{r}
# get n count per treatment
ndata <- ddply(dat, c("Algae", "Time_post_infection", "Repeat.Date."), summarise, N = length("Larvae")) 
head(ndata)
n_Figure <- ddply(ndata, c("Algae", "Time_post_infection"), summarise, N = length(Repeat.Date.))
n_Figure
write_csv(n_Figure, "1d_n.csv")
```




